### ISSUE TITLE
Plot Fitting Bug

### ISSUE THREAD

**Issue by OhadNir9** [EddLabs/eddington#100]
When trying to plot fitting, there's a bug (maybe in the new version of matplotlib) that prevents from showing the fit graph.
How to reproduce:
Open Eddington-Gui via "briefcase dev", load excel file, choose sheet and function and hit "Plot Fitting".
![14](https://user-images.githubusercontent.com/57434766/95167175-d8a47c00-07b7-11eb-914d-3da8c898ff23.png)
My repos are even with the upstream repo's

Edit:
Line 256 in plot.py looks kinda sus. I think ax.legend doesn't expect a boolean.
![15](https://user-images.githubusercontent.com/57434766/95168236-aeec5480-07b9-11eb-81f6-8c49484a7c97.png)

**Comment by saroad2** [comment]
hey @OhadNir9, Thanks for the bug detection!
Fixed it and release a new version of *Eddington*.

When developing on Eddington-GUI run `pip install -U eddington`, and the problem should be fixed.
