### ISSUE TITLE
Remove usage of xlrd

### ISSUE THREAD

**Issue by saroad2** [EddLabs/eddington#24]
In order to read excel files, we use the [xlrd](https://github.com/python-excel/xlrd) module.
At the moment, this repo is archived and no longer maintained.

Moving forward, we should replace xlrd with a more common library for reading excel files, [openpyxl](https://openpyxl.readthedocs.io/en/stable/) for example, as suggested by xlrd.

**Comment by OhadNir9** [comment]
I'm on it.

**Comment by OhadNir9** [comment]
Issue should be marked as closed.

**Comment by saroad2** [comment]
Indeed it is closed :)
