### ISSUE TITLE
Save FitData to Excel file

### ISSUE THREAD

**Issue by saroad2** [EddLabs/eddington#52]
One should be able to save `FitData` object to an excel file. Example code:

```python
from eddington import linear, FitData
from pathlib import Path

data = FitData.random(linear)
output_path = Path("/path/to/output.xlsx")

data.save_excel(output_path)
```

**Comment by OhadNir9** [comment]
I'm on it

**Comment by OhadNir9** [comment]
In what format do you want the FitData object to be saved? 

**Option 1:**
<table class="tg">
<thead>
  <tr>
    <th class="tg-0lax"></th>
    <th class="tg-0lax">x</th>
    <th class="tg-0lax">xerr</th>
    <th class="tg-0lax">y</th>
    <th class="tg-0lax">yerr</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0lax">rec. 1</td>
    <td class="tg-0lax"></td>
    <td class="tg-0lax"></td>
    <td class="tg-0lax"></td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">rec. 2</td>
    <td class="tg-0lax"></td>
    <td class="tg-0lax"></td>
    <td class="tg-0lax"></td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">rec .3</td>
    <td class="tg-0lax"></td>
    <td class="tg-0lax"></td>
    <td class="tg-0lax"></td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0lax">rec .4</td>
    <td class="tg-0lax"></td>
    <td class="tg-0lax"></td>
    <td class="tg-0lax"></td>
    <td class="tg-0lax"></td>
  </tr>
</tbody>
</table>
<br><br>

**Option 2:**

Export to excel the full raw data property, along with the other properties (records_indices, column indicators, etc.)

**Comment by saroad2** [comment]
Option 1, but extended. here's an example:

```python
from collections import OrderedDict
from pathlib import Path

from eddington import FitData

raw_data = OrderedDict(
    [
        ("a", [1, 2, 3]),
        ("b", [4, 5, 6]),
        ("c", [7, 8, 9]),
        ("d", [10, 11, 12]),
        ("e", [13, 14, 15]),
        ("f", [16, 17, 18]),
    ]
)
fit_data = FitData(
    data=raw_data, x_column="b", xerr_column="c", y_column="a", yerr_column="f"
)
output = Path("/path/to/output.excel")
fit_data.save_excel(output)
```

As you can see, we have the selected columns which are *a*, *b*, *c* and *f* (not in that order), but also have additional columns *d* and *e*. The output excel file should contain **all of those columns**, *d* and *e* included.

The reason is that if I want to reload the data later, like that:
```python
...   # later in the code
new_fit_data = FitData.read_from_excel(output, sheet_name)
```

I'll get the exact same data that I saved.

The same goes for #53 .
