### ISSUE TITLE
Toggle axes to logarithmic scale

### ISSUE THREAD

**Issue by HadarGreener** [EddLabs/eddington#94]
Add option to toggle axes to log scale

**Comment by OhadNir9** [comment]
I'm on it

**Comment by saroad2** [comment]
@OhadNir9 , Awesome! Let me know if you need help.

Pay attention that we need to toggle logarithmic scale **both in the x axis and y axis** and to add this ability also in the **CLI**.

**Comment by saroad2** [comment]
Fixed in #104
