### ISSUE TITLE
Hyperbolic function in GUI library

### ISSUE THREAD

**Issue by HadarGreener** [EddLabs/eddington#96]
Add hyperbolic function to GUI library

**Comment by saroad2** [comment]
The hyperbolic fitting function is actually supported in the library in the following form:

![CodeCogsEqn](https://user-images.githubusercontent.com/19425795/95011313-69ece480-0638-11eb-8688-e8251ece1b6d.gif)


Can you be more specific about the exact function you are referring to?

**Comment by saroad2** [comment]
It seems that the function you are looking for is already implemented. therefore, closing the issue.
If you meant something else, feel free to reopen the issue
